services:
  web:
    container_name: django-ecommerce
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  elastic_search:
      container_name: elasticsearch
      image: elasticsearch:8.17.3
      ports:
        - 9200:9200
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      volumes:
        - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
  postgres_data: