# Generated by Django 5.1.5 on 2025-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productquantity",
            name="added_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productquantity",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
