# Generated by Django 5.1.5 on 2025-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0004_remove_product_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="cart_products",
                to="products.product",
            ),
        ),
    ]
