# Generated by Django 5.1.5 on 2025-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_products"),
        ("products", "0005_product_bought_by_product_sold_by_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="cart_products", to="products.product"
            ),
        ),
    ]
