# Generated by Django 5.1.5 on 2025-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_productquantity_added_on_productquantity_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productquantity",
            name="bought_item",
            field=models.BooleanField(default=False),
        ),
    ]
