# Generated by Django 5.1.5 on 2025-03-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_productquantity_bought_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="productquantity",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productquantity",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_quantity",
                to="cart.cart",
            ),
        ),
    ]
