# Generated by Django 5.1.5 on 2025-03-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productquantity",
            name="bought_item",
        ),
    ]
