# Generated by Django 5.1.5 on 2025-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_productquantity_bought_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productquantity",
            name="total_price",
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
    ]
