# Generated by Django 5.1.5 on 2025-03-07 14:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ED", "Electronics Devices"),
                            ("HA", "Home Appliances"),
                            ("FA", "Fashion Accessories"),
                            ("SE", "Sports Equipment"),
                            ("BS", "Books & Stationery"),
                            ("BP", "Beauty Products"),
                            ("TG", "Toys & Games"),
                            ("GI", "Grocery Items"),
                            ("FD", "Furniture & Decor"),
                            ("HW", "Health & Wellness"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("discount_percentage", models.FloatField(blank=True, null=True)),
                ("discounted_price", models.FloatField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "bought_by",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.GenerateProfileImagePath(),
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="products.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
