# Generated by Django 5.1.5 on 2025-03-07 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bought_by",
            field=models.ManyToManyField(
                related_name="orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
