# Generated by Django 5.1.5 on 2025-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0002_review_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="cart_products", to="cart.cart"
            ),
        ),
    ]
