# Generated by Django 5.1.5 on 2025-03-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_bought_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="bought_by",
        ),
    ]
