# Generated by Django 5.1.5 on 2025-01-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cart",
        ),
    ]
