# Generated by Django 5.1.5 on 2025-03-05 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_bought_by_product_sold_by_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bought_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
