# Generated by Django 5.1.5 on 2025-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="final_price",
        ),
    ]
