# Generated by Django 5.1.5 on 2025-04-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_total_order_final_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-ordered_on"]},
        ),
    ]
