# Generated by Django 5.1.5 on 2025-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_discounted_price_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
